apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: skims-istiocontrolplane
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway
      label:
        istio: ingressgateway
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"      

