kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
  volumeMode: Filesystem
