apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: core
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: core-api
  type: ClusterIP

