kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: config
          secret:
            secretName: loki
            defaultMode: 420
        - name: storage
          persistentVolumeClaim:
            claimName: loki
      containers:
        - name: loki
          image: grafana/loki:2.0.0
          args:
            - '-config.file=/etc/loki/loki.yaml'
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 4800
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: sk-dev-eks-devops-worker-node
      serviceAccountName: loki
      serviceAccount: loki
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        fsGroup: 10001
      affinity: {}
      schedulerName: default-scheduler
# clusterIP나 Headless의 ServiceName을 일치 시키지 않아도 됨. 그러나 serviceName항목은 있어야 함.
  serviceName: loki-headless

