kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
subjects:
  - kind: ServiceAccount
    name: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki
