kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
rules:
  - verbs:
      - use
    apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - loki

