# Source: kiali-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: istio-system
  labels:
    helm.sh/chart: kiali-server-1.50.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v1.50.0"
    app.kubernetes.io/version: "v1.50.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali"
  annotations:
spec:
  ports:
  - name: http-kiali
    protocol: TCP
    port: 20001
  - name: http-metrics
    protocol: TCP
    port: 8080
  selector:
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
  type: ClusterIP
