kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: scouter-server
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: scouter-server
    app.kubernetes.io/name: scouter-server
    app: scouter-server
    component: server
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    #volume.kubernetes.io/selected-node: ip-10-12-102-169.ap-northeast-2.compute.internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
