apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  ports:
  - name: http
    port: 9100
    protocol: TCP
  type: ClusterIP
  selector:
    k8s-app: node-exporter

