kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: config
          configMap:
            name: promtail
            defaultMode: 420
        - name: run
          hostPath:
            path: /run/promtail
            type: ''
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
            type: ''
        - name: pods
          hostPath:
            path: /var/log/pods
            type: ''
      containers:
        - name: promtail
          image: grafana/promtail:2.0.0
          args:
            - '-config.file=/etc/promtail/promtail.yaml'
            - '-client.url=http://loki:3100/loki/api/v1/push'
          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - name: docker
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: pods
              readOnly: true
              mountPath: /var/log/pods
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: promtail
      serviceAccount: promtail

