kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promtail
