##################################################################################################
# skimscnr service
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: skims-cnr-api
  labels:
    app: skims-cnr-api    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skims-cnr-api
  template:
    metadata:
      labels:
        app: skims-cnr-api
    spec:
      containers:
      - name: skims-cnr-api
        image: 504441673365.dkr.ecr.ap-northeast-2.amazonaws.com/skimscnr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: 200m
        #   limits:
        #     cpu: 1200m

---
apiVersion: v1
kind: Service
metadata:
  name: service-skims-cnr-api
spec:
  selector:
    app: skims-cnr-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
##################################################################################################
# skimscnr hpa
##################################################################################################
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: skims-cnr-hpa
#   namespace: default
# spec:
#   minReplicas: 1
#   maxReplicas: 5
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: skims-cnr-api
#   metrics:
#   - resource:
#       name: cpu
#       target:
#         averageUtilization: 50
#         type: Utilization
#     type: Resource
#   - resource:
#       name: memory
#       target:
#         averageValue: 1Gi
#         type: AverageValue
#     type: Resource
