apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: logging
  annotations:
    #prometheus.io/scrape: 'true'
    #prometheus.io/port: '9200'
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - name: elasticsearch-rest
      nodePort: 30920
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: elasticsearch-nodecom
      nodePort: 30930
      port: 9300
      protocol: TCP
      targetPort: 9300

