kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
      #  annotations:
      #    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
