kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: 'true'
  fsType: ext4
  type: gp2
    #reclaimPolicy: Delete
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
